project:
  type: website
  output-dir: docs

website:
  title: "KandibandaKashyap"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - favorites.qmd
      - hobbies.qmd
      - Placeholder1.qmd
      - Placeholder2.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

