---
title: "KandibandaKashyap"
image: pic (Medium).jpg
resources: cv_jfrench.pdf
about: 
  id: jfrench-heading
  template: jolla
  image-shape: rounded
  image-width: 15em
  links:
    - text: Email
      icon: envelope
      href: mailto:kkandiba@gmu.edu
    - text: GitHub
      icon: github
      href: https://github.com/kandibandakashyap
    - text: Linkedin
      icon: linkedin
      href: https://www.linkedin.com/in/kashyap-kandibanda
---

::: {#jfrench-heading}
I am pursuing an MS in Data Analytics Engineering at George Mason University. With a background in mechanical engineering from Amrita School of Engineering, I have honed my problem-solving and data analysis skills. I'm passionate about using data-driven insights to solve complex problems, improve processes, and drive innovation. I also have experience in leadership roles through extracurricular activities, such as organizing workshops and volunteer projects, reflecting my teamwork and management abilities.

I have gained hands-on experience through various roles, including a backend intern at GrootLabs, where I worked on optimizing backend systems for performance and scalability. I also served as an associate at GoldSquare Avenues, contributing to key decision-making and project management.

My academic project on fracture mechanics analysis of materials with voids, using Finite Element simulations in Abaqus, involved detailed mesh convergence analysis and the study of fracture energy concerning void proximity. The project, aimed at industries like automotive and aerospace, provided insights into material integrity and fracture behavior, further enhancing my expertise in data analytics and engineering. Additionally, during my internship at Singareni Collieries Company Limited, I explored various manufacturing techniques and identified process improvements to optimize production efficiency.
:::
